# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :beta do
    increment_build_number(xcodeproj: "todo.xcodeproj")
    match(
      type: "appstore",
      readonly: true,
      api_key: app_store_connect_api_key(
        key_id: "7Z5UW49WQ8",
        issuer_id: "d11ea7cf-c11f-4649-94e5-051e7f797908",
        key_filepath: "./fastlane/AuthKeys/AuthKey_7Z5UW49WQ8.p8",
      )
    )
    # build_app(scheme:"todo")
    build_app(
      workspace: "todo.xcworkspace",
      scheme: "todo",
      clean: true,
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        provisioningProfiles: {
          "in.nitinvarda.todo" => "match AppStore in.nitinvarda.todo"
        }
      })
    upload_to_testflight(
      api_key:app_store_connect_api_key(
        key_id: "7Z5UW49WQ8",
        issuer_id: "d11ea7cf-c11f-4649-94e5-051e7f797908",
        key_filepath: "./fastlane/AuthKeys/AuthKey_7Z5UW49WQ8.p8",
        duration: 1200, # optional (20 mins token)
        in_house: false
      )
    )
  end
end
