# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Setup keychain"
  lane :setup_keychain do
    delete_keychain(
      name: keychain-name
    ) if File.exist? File.expand_path("~/Library/Keychains/fastlane-ios-build.keychain-db")

    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :build_and_publish_ios  do

    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'], # from table 1.0
      issuer_id: ENV['APPLE_ISSUER_ID'],  # from table 1.0
      key_filepath: ENV['APPLE_KEY_PATH'],  # from table 1.0
      in_house: false
    )
    
    match(
      type: "appstore", # use development | appstore | ad-hoc
      app_identifier: 'in.nitinvarda.todo', # if you have other extensions like oneginal then pass an array [com.example, com.example.OneSignalNotificationServiceExtension]
      verbose: true,
      api_key: api_key,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )

    increment_build_number(xcodeproj: "todo.xcodeproj")
    build_app(
      scheme: "todo",
      workspace: "todo.xcworkspace",
      export_method: "app-store",
      clean: true,
      verbose: true,
      export_options: {
        export_method: "app-store",
        team_id: 'YB7RTTYCHC',
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: api_key,
      changelog: "New Build"
    )
  end
end
