-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2rDxBWB+GInsuLf2
0mqTZMRr6JZcX8RmeTbwzDttMOigCgYIKoZIzj0DAQehRANCAARqXfdfpm1acrtX
JfCmzTONZ+mlsg6Q7U2Ww55uDey7mPNTh5rFbH5qJAhYKI+5Fcrn0kRAIidom9jB
+XcBjyk/
-----END PRIVATE KEY-----