name: Deploy to Testflight

on:   
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-14
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_KEYCHAIN_NAME: ${{secrets.MATCH_KEYCHAIN_NAME}}
      MATCH_KEYCHAIN_PASSWORD: ${{secrets.MATCH_KEYCHAIN_PASSWORD}}
      APPLE_ISSUER_ID : ${{secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID : ${{secrets.APPLE_KEY_ID }}
      APPLE_API_KEY_BASE64: ${{secrets.APPLE_API_KEY_BASE64}}
      APPLE_KEY_PATH : ${{secrets.APPLE_KEY_PATH}}
      DEVELOPER_APP_ID : ${{secrets.DEVELOPER_APP_ID }}
      DEVELOPER_APP_IDENTIFIER : ${{secrets.DEVELOPER_APP_IDENTIFIER }}
      FASTLANE_APP_ID : ${{secrets.FASTLANE_APP_ID }}
      GIT_AUTHORIZATION : ${{secrets.GIT_AUTHORIZATION }}
      FASTLANE_USER: ${{secrets.FASTLANE_USER}}
      FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
      VERSION: ${{ github.event.inputs.version }}
      RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
    
      
    steps:
      - name: Use Xcode 16
        run: |
          ls /Applications/
          sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install Node.js dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install
  
      - name: Install dependencies
        working-directory: ios
        run: |
          bundle install      
    
      - name: Create custom keychain
        run: |
          KEYCHAIN_NAME=$MATCH_KEYCHAIN_NAME.keychain-db
          KEYCHAIN_PASSWORD=password
          KEYCHAIN_PATH="$HOME/Library/Keychains/$KEYCHAIN_NAME"
      
          # Create the keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
      
          # Unlock it
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
      
          # Add to keychain list
          security list-keychains -s "$KEYCHAIN_PATH"

      - name: Decode API key
        run: |
          echo "${{ secrets.APPLE_API_KEY_BASE64 }}" | base64 -d > ios/${{secrets.APPLE_KEY_PATH}}

      - name: Setup CI
        working-directory: ios
        run: bundle exec fastlane setting_continious_integration --verbose

      - name: Configure match
        working-directory: ios
        run: bundle exec fastlane configure_match --verbose
      
      - name: Check installed profiles
        run: ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      
      - name: Check code signing identities
        run: security find-identity -v -p codesigning

      - name: build project
        working-directory: ios
        run: bundle exec fastlane build_project --verbose

      - name: upload to TestFlight
        working-directory: ios
        run: bundle exec fastlane upld_to_testflight --verbose