name: Deploy to Testflight

on:   
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_KEYCHAIN_NAME: ${{secrets.MATCH_KEYCHAIN_NAME}}
      MATCH_KEYCHAIN_PASSWORD: ${{secrets.MATCH_KEYCHAIN_PASSWORD}}
      APPLE_ISSUER_ID : ${{secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID : ${{secrets.APPLE_KEY_ID }}
      APPLE_KEY_PATH: ${{secrets.APPLE_KEY_PATH}}
      DEVELOPER_APP_ID : ${{secrets.DEVELOPER_APP_ID }}
      DEVELOPER_APP_IDENTIFIER : ${{secrets.DEVELOPER_APP_IDENTIFIER }}
      FASTLANE_APP_ID : ${{secrets.FASTLANE_APP_ID }}
      GIT_AUTHORIZATION : ${{secrets.GIT_AUTHORIZATION }}
      FASTLANE_USER: ${{secrets.FASTLANE_USER}}
      FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
      VERSION: ${{ github.event.inputs.version }}
      RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install Node.js dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install
  
      - name: Install dependencies
        working-directory: ios
        run: |
          bundle install      

      - name: Setup keychain
        working-directory: ios
        run: bundle exec fastlane setup_keychain

      - name: Build and Publish to TestFlight
        working-directory: ios
        run: bundle exec fastlane build_and_publish_ios