name: Deploy to Testflight

on:   
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or commit to build from"
        default: "main"
        required: false
      version:
        description: 'Set the version for the build'
        required: false
      releaseNotes:
        description: 'Release notes for the deployment'
        required: false

jobs:
  build:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_KEYCHAIN_NAME: build.keychain
      MATCH_KEYCHAIN_PASSWORD: fastlane
      APPLE_ISSUER_ID : ${{secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID : ${{secrets.APPLE_KEY_ID }}
      DEVELOPER_APP_ID : ${{secrets.DEVELOPER_APP_ID }}
      DEVELOPER_APP_IDENTIFIER : ${{secrets.DEVELOPER_APP_IDENTIFIER }}
      FASTLANE_APP_ID : ${{secrets.FASTLANE_APP_ID }}
      GIT_AUTHORIZATION : ${{secrets.GIT_AUTHORIZATION }}
      FASTLANE_USER: ${{secrets.FASTLANE_USER}}
      FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
      VERSION: ${{ github.event.inputs.version }}
      RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
    
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install Node.js dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install
  
      - name: Install dependencies
        working-directory: ios
        run: |
          bundle install


      - name: Set up signing keychain
        run: |
            security create-keychain -p fastlane build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p fastlane build.keychain
            security set-keychain-settings build.keychain

      - name: Check code signing identities
        run: security find-identity -v -p codesigning
      

      - name: Run Fastlane lane
        working-directory: ios
        run: bundle exec fastlane beta --verbose
       

          

