name: Deploy to Testflight

on:   
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_KEYCHAIN_NAME: login.keychain-db
      MATCH_KEYCHAIN_PASSWORD: 4986
      APPLE_ISSUER_ID : ${{secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_ID : ${{secrets.APPLE_KEY_ID }}
      APPLE_KEY_PATH: "fastlane/Authkeys/AuthKey_7Z5UW49WQ8.p8"
      DEVELOPER_APP_ID : ${{secrets.DEVELOPER_APP_ID }}
      DEVELOPER_APP_IDENTIFIER : ${{secrets.DEVELOPER_APP_IDENTIFIER }}
      FASTLANE_APP_ID : ${{secrets.FASTLANE_APP_ID }}
      GIT_AUTHORIZATION : ${{secrets.GIT_AUTHORIZATION }}
      FASTLANE_USER: ${{secrets.FASTLANE_USER}}
      FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
      VERSION: ${{ github.event.inputs.version }}
      RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install Node.js dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install
  
      - name: Install dependencies
        working-directory: ios
        run: |
          bundle install      

      - name: Setup CI
        working-directory: ios
        run: bundle exec fastlane setting_continious_integration --verbose

      - name: Configure match
        working-directory: ios
        run: bundle exec fastlane configure_match --verbose

      - name: Increment build number
        working-directory: ios
        run: bundle exec fastlane inc_build_number --verbose

      - name: Check installed profiles
        run: ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      
      - name: Check code signing identities
        run: security find-identity -v -p codesigning

      - name: build project
        working-directory: ios
        run: bundle exec fastlane build_project --verbose

      - name: upload to TestFlight
        working-directory: ios
        run: bundle exec fastlane upld_to_testflight --verbose