name: Deploy to Testflight

on:   
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or commit to build from"
        default: "main"
        required: false
      version:
        description: 'Set the version for the build'
        required: false
      releaseNotes:
        description: 'Release notes for the deployment'
        required: false

jobs:
  build:
    runs-on: macos-latest
    
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
      - name: Install Node.js dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install
  
      - name: Install dependencies
        working-directory: ios
        run: |
          bundle install

      - name: Run Fastlane lane
        working-directory: ios
        run: bundle exec fastlane beta --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          VERSION: ${{ github.event.inputs.version }}
          RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}

          

